### ISSUE TITLE
Naprawienie błędu kompilacji, podczas prób poza konkursem

### ISSUE THREAD

**Issue by JanekAdamek** [Krzysiek-Mistrz/npg-projekt-zgadywanka#11]
Aktualnie gdy użytkownik przegra rozgrywkę program pyta się go, czy chce kontynuować poza konkursem. Nie do końca po prawnie to działa. Cały czas pyta się o kontynuację po każdym błędnym wybraniu liczby... Co więcej jeśli użytkownik zgadnie "poza konkursem", to po wiadomości "wygrałeś" kompilator pokazuje error.

**Comment by JanekAdamek** [comment]
Nowe zadanie, naprawa funkcjonalności po przegranej

**Comment by Krzysiek-Mistrz** [comment]
Pytanie o kontynuację gry poza konkursem powinno teraz pojawić się tylko raz, gdy użytkownik przekroczy liczbę prób, problem uznaję za rozwiązany
